### ISSUE TITLE
Normalization and preprocessing

### ISSUE THREAD

**Issue by RuoyuGuo** [wooseoklee4/AP-BSN#6]
Hi, Thank you for releasing your codes.

May I ask several questions?

1. Based on my understanding, you crop the SIDD dataset into 512 * 512 patches with 128 overlappings. So if one patch is [100:100+512, 100:100+512],  then the next patch will be [100:612, 100+512-128: 100+512-128+512].
2. The input tensor is the cropped patch, a 120 * 120 tensor will be generated by cropping the patch. So the actual input tensor will be 120 * 120
3. How do you normalise your input data? I can see somewhere there is a function called ```normalize(...)``` in ```denoise_dataset.py``` but where this function is called?  It uses the std and mean to normalize data, how the std and mean are generated?

Thank you for your time!

**Comment by wooseoklee4** [comment]
Hi, RuoyuGuo.

Thanks for your interest to my work.

To the first and second questions, Yes. As your thought, we randomly cropped 120x120 patches during training. But instead of loading full SIDD image for cropping training patches, we firstly prepared the training dataset by cropping 512x512 with 128 overlapping for more faster loading. And your understanding for this preparing step is right.

To the third question, we did NOT use normalization for images. Actually, we tested on both using/not using normalization of images, but we cannot find big difference. That `normalize(...)` is a deprecated function which is does not used in this project.
Sorry for your confusing due to remaining functions.

Thank you!

**Comment by RuoyuGuo** [comment]
> 

Thank you for your reply! Your answers definitely solved my problems. May I have the last question? So in your experiments, the pixel intensity of non-normalized images ranges from 0 to 255. Is this correct?

**Comment by wooseoklee4** [comment]
Yes, the input/output image have a pixel range of [0, 255]

**Comment by RuoyuGuo** [comment]
Again, thank you! A very amazing study on denoising!
