### ISSUE TITLE
Question about the noise correlation

### ISSUE THREAD

**Issue by Wang-XIaoDingdd** [wooseoklee4/AP-BSN#7]
Thank you for your great work!

In Figure 2, you provide the analysis of spatial correlation on real-world noise. I try to calculate the accurate value of the correlation and reproduce the plots in Figure 2. Specifically, I divide the neighbor noise values by the center noise value, while my results seem different from Figure 2:
![myplot_3](https://user-images.githubusercontent.com/47033238/192224121-5a93c601-c83f-455a-a22e-66fc078daafb.png)
Can you provide more details about how Figure 2 is generated? It would be amazing if the code snippet can be provided!! Thanks :)

**Comment by wooseoklee4** [comment]
Hi Wang-XIaoDingdd,
Thank you for your question!

To measure the correlation of relative position, we divided the co-variance of noises in relative position with the variance of noise as the definition of correlation.
Also, I think you can adjust the color(reversing color map) and value range if you want to draw the figure similarly.
Because, from the analysis, the correlation does not shrink to zero but remains small. (you can see the range of the legend in figure 2.)

In addition, we measured noise correlation with the SIDD training dataset including all types of smartphones for more detail.

I think you can easily modify your code for this, as the measuring part would be easier compared to what you already have done.
Please understand that I cannot provide the code immediately due to the code is quite messy.
After, If you still fail to measure, I will provide the code after organizing the code.

Thank you:)

**Comment by Mrhard1999** [comment]
Hello, I just started this aspect and want to reproduce the whole code. Is your project based on Linux environment?

**Comment by wooseoklee4** [comment]
Hi Mrhard1999,

Thanks for your question.
All the experiments in the paper are done with Ubuntu operating system.

I'll be glad if you make another issue or give an email during your reproducing.

Thanks.

**Comment by hyunW3** [comment]
Hello,
I'm little confused with "To measure the correlation of relative position, we divided the co-variance of noises in relative position with the variance of noise as the definition of correlation."

Could you give me more details of it? (simple pseudo code would help me understand)
